export interface Farm {
  id: string;
  name: string;
  location: string;
  district: string;
  rating: number;
  image: string;
  tags: string[];
  plansCount: number;
  category: string;
}

export const CROP_CATEGORIES = [
  "All",
  "Food Crops",
  "Cash Crops",
  "Oilseeds",
  "Fruits",
  "Vegetables",
];

export const LOCATIONS = [
  "All",
  "Adilabad",
  "Ananthapuram",
  "Chittoor",
  "East Godavari",
  "Guntur",
  "Kadapa",
  "Kamareddy",
  "Karimnagar",
  "Khammam",
  "Krishna",
  "Kurnool",
  "Mahaboobnagar",
  "Medak",
  "Nalgonda",
  "Nellore",
  "Nizamabad",
  "Rangareddy",
  "Srikakulam",
  "Vizianagaram",
  "Warangal",
];

export const ALL_FARMS: Farm[] = [
  {
    id: "1",
    name: "Chilli",
    location: "Guntur, Andhra Pradesh",
    district: "Guntur",
    rating: 4.9,
    image: "/images/guntur-chili.jpg",
    tags: ["Chili", "Cash Crops"],
    category: "Cash Crops",
    plansCount: 15,
  },
  {
    id: "3",
    name: "Coconut",
    location: "East Godavari, Andhra Pradesh",
    district: "East Godavari",
    rating: 4.9,
    image: "/images/coconut.png",
    tags: ["Coconut", "Fruits"],
    category: "Fruits",
    plansCount: 10,
  },
  {
    id: "4",
    name: "Rice",
    location: "Vijayawada, Andhra Pradesh",
    district: "Krishna",
    rating: 4.7,
    image: "/images/indian-paddy.jpg",
    tags: ["Rice", "Food Crops"],
    category: "Food Crops",
    plansCount: 20,
  },
  {
    id: "5",
    name: "Turmeric",
    location: "Nizamabad, Telangana",
    district: "Nizamabad",
    rating: 4.9,
    image: "/images/turmeric.png",
    tags: ["Turmeric", "Cash Crops"],
    category: "Cash Crops",
    plansCount: 14,
  },
  {
    id: "6",
    name: "Groundnut",
    location: "Ananthapuram, Andhra Pradesh",
    district: "Ananthapuram",
    rating: 4.8,
    image: "/images/groundnut.png",
    tags: ["Groundnut", "Oilseeds"],
    category: "Oilseeds",
    plansCount: 18,
  },
  {
    id: "7",
    name: "Mango",
    location: "Krishna, Andhra Pradesh",
    district: "Krishna",
    rating: 4.9,
    image: "/images/mango-orchard.png",
    tags: ["Mango", "Fruits"],
    category: "Fruits",
    plansCount: 9,
  },
  {
    id: "8",
    name: "Pulses",
    location: "Khammam, Telangana",
    district: "Khammam",
    rating: 4.6,
    image: "/images/pulses.png",
    tags: ["Red Gram", "Food Crops"],
    category: "Food Crops",
    plansCount: 11,
  },
  {
    id: "9",
    name: "Banana",
    location: "Kadapa, Andhra Pradesh",
    district: "Kadapa",
    rating: 4.7,
    image: "/images/banana-farm.png",
    tags: ["Banana", "Fruits"],
    category: "Fruits",
    plansCount: 13,
  },
  {
    id: "10",
    name: "Onion",
    location: "Kurnool, Andhra Pradesh",
    district: "Kurnool",
    rating: 4.5,
    image: "/images/onion-harvest.png",
    tags: ["Onion", "Vegetables"],
    category: "Vegetables",
    plansCount: 16,
  },
  {
    id: "11",
    name: "Cashew nut",
    location: "Srikakulam, Andhra Pradesh",
    district: "Srikakulam",
    rating: 4.8,
    image: "/images/cashew-plantation.png",
    tags: ["Cashew nut", "Fruits"],
    category: "Fruits",
    plansCount: 7,
  },
  {
    id: "12",
    name: "Citrus",
    location: "Nellore, Andhra Pradesh",
    district: "Nellore",
    rating: 4.7,
    image: "/images/citrus-grove.png",
    tags: ["Citrus", "Fruits"],
    category: "Fruits",
    plansCount: 8,
  },
  {
    id: "13",
    name: "Tobacco",
    location: "Nalgonda, Telangana",
    district: "Nalgonda",
    rating: 4.6,
    image: "/images/tobacco-farm.png",
    tags: ["Tobacco", "Cash Crops"],
    category: "Cash Crops",
    plansCount: 5,
  },
  {
    id: "14",
    name: "Sugarcane",
    location: "Kamareddy, Telangana",
    district: "Kamareddy",
    rating: 4.8,
    image: "/images/sugarcane-plantation.png",
    tags: ["Sugarcane", "Cash Crops"],
    category: "Cash Crops",
    plansCount: 12,
  },
  {
    id: "15",
    name: "Gherkins",
    location: "Mahaboobnagar, Telangana",
    district: "Mahaboobnagar",
    rating: 4.7,
    image: "/images/millets.png",
    tags: ["Gherkins", "Vegetables"],
    category: "Vegetables",
    plansCount: 9,
  },
  {
    id: "17",
    name: "Groundnut",
    location: "Chittoor, Andhra Pradesh",
    district: "Chittoor",
    rating: 4.6,
    image: "/images/groundnut.png",
    tags: ["Groundnut", "Oilseeds"],
    category: "Oilseeds",
    plansCount: 11,
  },
  {
    id: "18",
    name: "Mango",
    location: "Mahaboobnagar, Telangana",
    district: "Mahaboobnagar",
    rating: 4.8,
    image: "/images/mango-orchard.png",
    tags: ["Mango", "Fruits"],
    category: "Fruits",
    plansCount: 6,
  },
  {
    id: "19",
    name: "Gherkins",
    location: "Rangareddy, Telangana",
    district: "Rangareddy",
    rating: 4.7,
    image: "/images/millets.png",
    tags: ["Gherkins", "Vegetables"],
    category: "Vegetables",
    plansCount: 8,
  },
  {
    id: "21",
    name: "Gherkins",
    location: "Karimnagar, Telangana",
    district: "Karimnagar",
    rating: 4.6,
    image: "/images/millets.png",
    tags: ["Gherkins", "Vegetables"],
    category: "Vegetables",
    plansCount: 10,
  },
  {
    id: "22",
    name: "Gongura",
    location: "Guntur, Andhra Pradesh",
    district: "Guntur",
    rating: 4.8,
    image: "/images/gongura.png",
    tags: ["Gongura", "Vegetables"],
    category: "Vegetables",
    plansCount: 8,
  },
  {
    id: "23",
    name: "Brinjal",
    location: "Krishna, Andhra Pradesh",
    district: "Krishna",
    rating: 4.7,
    image: "/images/brinjal.png",
    tags: ["Brinjal", "Vegetables"],
    category: "Vegetables",
    plansCount: 12,
  },
  {
    id: "24",
    name: "Okra",
    location: "Warangal, Telangana",
    district: "Warangal",
    rating: 4.6,
    image: "/images/okra.png",
    tags: ["Okra", "Vegetables"],
    category: "Vegetables",
    plansCount: 10,
  },
  {
    id: "25",
    name: "Tomato",
    location: "Nalgonda, Telangana",
    district: "Nalgonda",
    rating: 4.5,
    image: "/images/tomato.png",
    tags: ["Tomato", "Vegetables"],
    category: "Vegetables",
    plansCount: 15,
  },
  {
    id: "26",
    name: "Cabbage",
    location: "Medak, Telangana",
    district: "Medak",
    rating: 4.4,
    image: "/images/cabbage.png",
    tags: ["Cabbage", "Vegetables"],
    category: "Vegetables",
    plansCount: 7,
  },
  {
    id: "27",
    name: "Cauliflower",
    location: "Karimnagar, Telangana",
    district: "Karimnagar",
    rating: 4.6,
    image: "/images/cauliflower.png",
    tags: ["Cauliflower", "Vegetables"],
    category: "Vegetables",
    plansCount: 9,
  },
  {
    id: "28",
    name: "Cucumber",
    location: "Rangareddy, Telangana",
    district: "Rangareddy",
    rating: 4.7,
    image: "/images/cucumber.png",
    tags: ["Cucumber", "Vegetables"],
    category: "Vegetables",
    plansCount: 11,
  },
  {
    id: "29",
    name: "Carrot",
    location: "Adilabad, Telangana",
    district: "Adilabad",
    rating: 4.8,
    image: "/images/carrot.png",
    tags: ["Carrot", "Vegetables"],
    category: "Vegetables",
    plansCount: 6,
  },
  {
    id: "30",
    name: "Radish",
    location: "Nizamabad, Telangana",
    district: "Nizamabad",
    rating: 4.5,
    image: "/images/radish.png",
    tags: ["Radish", "Vegetables"],
    category: "Vegetables",
    plansCount: 8,
  },
  {
    id: "31",
    name: "Capsicum",
    location: "Kamareddy, Telangana",
    district: "Kamareddy",
    rating: 4.7,
    image: "/images/capsicum.png",
    tags: ["Capsicum", "Vegetables"],
    category: "Vegetables",
    plansCount: 10,
  },
  {
    id: "32",
    name: "Guava",
    location: "Mahaboobnagar, Telangana",
    district: "Mahaboobnagar",
    rating: 4.9,
    image: "/images/guava.png",
    tags: ["Guava", "Fruits"],
    category: "Fruits",
    plansCount: 5,
  },
  {
    id: "33",
    name: "Banana (Robusta)",
    location: "Kadapa, Andhra Pradesh",
    district: "Kadapa",
    rating: 4.8,
    image: "/images/banana-robusta.png",
    tags: ["Banana", "Fruits"],
    category: "Fruits",
    plansCount: 12,
  },
  {
    id: "34",
    name: "Banana (Nendran)",
    location: "Kurnool, Andhra Pradesh",
    district: "Kurnool",
    rating: 4.7,
    image: "/images/banana-robusta.png", // Reusing robusta as placeholder
    tags: ["Banana", "Fruits"],
    category: "Fruits",
    plansCount: 9,
  },
];
